/********************************************************************************
 * Copyright (c) 2026 EclipseSource and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License v. 2.0 are satisfied: GNU General Public License, version 2
 * with the GNU Classpath Exception which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 ********************************************************************************/

import * as fs from 'fs';
import * as path from 'path';
import { Command } from 'commander';
import { GLSPRepo, LOGGER, baseCommand } from '../../util';
import { configureRepoEnv, discoverRepos, resolveWorkspaceDir } from './common/utils';
import { BROWSER_BUNDLE_PATH } from './server-node';
import { VSIX_ID, WEB_VSIX_ID, discoverVsix, discoverWebVsix } from './vscode';

const DEFAULT_TARGET_DIR = 'examples/workflow-test';

export interface PlaywrightEnvOptions {
    dir: string;
    discoveredRepos: GLSPRepo[];
}

export function generatePlaywrightEnvContent(options: PlaywrightEnvOptions): string {
    const { dir, discoveredRepos } = options;
    const lines: string[] = [];

    lines.push('# Generated by: glsp repo playwright env');
    lines.push('# Regenerate this file after workspace changes.');
    lines.push('');

    lines.push('# Optional port overrides (uncomment to change defaults)');
    lines.push('# GLSP_SERVER_PORT=8081');
    lines.push('# STANDALONE_PORT=8082');
    lines.push('# STANDALONE_BROWSER_PORT=8083');
    lines.push('# THEIA_PORT=3000');
    lines.push('');

    const hasServerNode = discoveredRepos.includes('glsp-server-node');
    const hasClient = discoveredRepos.includes('glsp-client');

    if (hasServerNode && hasClient) {
        lines.push('# Standalone Node (WebSocket)');
        lines.push('GLSP_SERVER_START_CMD=glsp repo server-node start');
        lines.push('STANDALONE_START_CMD=glsp repo client start --external-server --no-open');
    } else {
        lines.push('# Standalone Node (WebSocket) — missing repos, uncomment when available');
        lines.push('# GLSP_SERVER_START_CMD=glsp repo server-node start');
        lines.push('# STANDALONE_START_CMD=glsp repo client start --external-server --no-open');
    }
    lines.push('');

    if (hasServerNode && hasClient) {
        const bundlePath = path.resolve(dir, 'glsp-server-node', BROWSER_BUNDLE_PATH);
        const bundleExists = fs.existsSync(bundlePath);
        lines.push('# Standalone Browser (Web Worker)');
        if (bundleExists) {
            lines.push(`STANDALONE_BROWSER_START_CMD=glsp repo client start --browser --external-server ${bundlePath} --no-open`);
        } else {
            LOGGER.warn(`Browser bundle not found at ${bundlePath}. Build glsp-server-node first.`);
            lines.push(`# STANDALONE_BROWSER_START_CMD=glsp repo client start --browser --external-server ${bundlePath} --no-open`);
        }
    } else {
        lines.push('# Standalone Browser (Web Worker) — missing repos, uncomment when available');
        lines.push('# STANDALONE_BROWSER_START_CMD=glsp repo client start --browser --external-server <bundle-path> --no-open');
    }
    lines.push('');

    const hasTheia = discoveredRepos.includes('glsp-theia-integration');
    if (hasTheia) {
        lines.push('# Theia');
        lines.push('THEIA_START_CMD=glsp repo theia start');
    } else {
        lines.push('# Theia — repo not found, uncomment when available');
        lines.push('# THEIA_START_CMD=glsp repo theia start');
    }
    lines.push('');

    const hasVscode = discoveredRepos.includes('glsp-vscode-integration');
    if (hasVscode) {
        const vscodeRepoDir = path.resolve(dir, 'glsp-vscode-integration');

        lines.push('# VSCode');
        lines.push(`VSCODE_VSIX_ID=${VSIX_ID}`);
        let vsixPath: string | undefined;
        try {
            vsixPath = discoverVsix(vscodeRepoDir);
        } catch {
            LOGGER.warn('VSIX file not found. Build and package the VSCode extension first.');
        }
        if (vsixPath) {
            lines.push(`VSCODE_VSIX_PATH=${vsixPath}`);
        } else {
            lines.push('# VSCODE_VSIX_PATH=<path-to-vsix>');
        }
        lines.push('');

        lines.push('# VSCode Web Extension');
        lines.push(`VSCODE_WEB_VSIX_ID=${WEB_VSIX_ID}`);
        let webVsixPath: string | undefined;
        try {
            webVsixPath = discoverWebVsix(vscodeRepoDir);
        } catch {
            LOGGER.warn('Web extension VSIX file not found. Build and package the web extension first.');
        }
        if (webVsixPath) {
            lines.push(`VSCODE_WEB_VSIX_PATH=${webVsixPath}`);
        } else {
            lines.push('# VSCODE_WEB_VSIX_PATH=<path-to-web-vsix>');
        }
    } else {
        lines.push('# VSCode — repo not found, uncomment when available');
        lines.push(`# VSCODE_VSIX_ID=${VSIX_ID}`);
        lines.push('# VSCODE_VSIX_PATH=<path-to-vsix>');
        lines.push('');
        lines.push('# VSCode Web Extension — repo not found, uncomment when available');
        lines.push(`# VSCODE_WEB_VSIX_ID=${WEB_VSIX_ID}`);
        lines.push('# VSCODE_WEB_VSIX_PATH=<path-to-web-vsix>');
    }
    lines.push('');

    return lines.join('\n');
}

export const PlaywrightEnvCommand: Command = baseCommand()
    .name('env')
    .description('Generate a .env file for Playwright testing')
    .option('-d, --dir <path>', 'Target directory where repos are cloned')
    .option('-t, --target-dir <path>', 'Target directory for the .env file (default: glsp-playwright/examples/workflow-test)')
    .option('-v, --verbose', 'Verbose output', false)
    .action(async (_cmdOptions: unknown, thisCmd: Command) => {
        const cli = thisCmd.opts<{ dir?: string; targetDir?: string; verbose: boolean }>();
        configureRepoEnv(cli);

        const dir = resolveWorkspaceDir(cli.dir);
        const discoveredRepos = discoverRepos(dir);

        const content = generatePlaywrightEnvContent({ dir, discoveredRepos });

        let targetDir: string;
        if (cli.targetDir) {
            targetDir = path.resolve(cli.targetDir);
        } else {
            const playwrightRepo = path.resolve(dir, 'glsp-playwright');
            if (!discoveredRepos.includes('glsp-playwright')) {
                throw new Error(`glsp-playwright repo not found in '${dir}'. Use --target-dir to specify an alternative output directory.`);
            }
            targetDir = path.resolve(playwrightRepo, DEFAULT_TARGET_DIR);
        }

        const envFile = path.resolve(targetDir, '.env');
        fs.mkdirSync(targetDir, { recursive: true });
        fs.writeFileSync(envFile, content, 'utf-8');
        LOGGER.info(`Generated ${envFile}`);
    });
