/********************************************************************************
 * Copyright (c) 2026 EclipseSource and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License v. 2.0 are satisfied: GNU General Public License, version 2
 * with the GNU Classpath Exception which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 ********************************************************************************/

import { expect } from 'chai';
import * as fs from 'fs';
import * as path from 'path';
import { GLSPRepo } from '../../util';
import { BROWSER_BUNDLE_PATH } from './server-node';
import { cleanupTempDir, createTempDir } from '../../../tests/helpers/test-helper';
import { generatePlaywrightEnvContent } from './playwright';

describe('playwright-env', () => {
    let tempDir: string;

    beforeEach(() => {
        tempDir = createTempDir();
    });

    afterEach(() => {
        cleanupTempDir(tempDir);
    });

    function createRepoDirs(...names: string[]): void {
        for (const name of names) {
            fs.mkdirSync(path.join(tempDir, name), { recursive: true });
        }
    }

    describe('generatePlaywrightEnvContent', () => {
        it('should include header comment', () => {
            const content = generatePlaywrightEnvContent({ dir: tempDir, discoveredRepos: [] });
            expect(content).to.contain('# Generated by: glsp repo playwright env');
        });

        it('should always include general section with server port, debug, and websocket path', () => {
            const content = generatePlaywrightEnvContent({ dir: tempDir, discoveredRepos: [] });
            expect(content).to.contain('GLSP_SERVER_PORT=8081');
            expect(content).to.contain('GLSP_SERVER_DEBUG=true');
            expect(content).to.contain('GLSP_WEBSOCKET_PATH=workflow');
        });

        it('should include port override comments without GLSP_SERVER_PORT', () => {
            const content = generatePlaywrightEnvContent({ dir: tempDir, discoveredRepos: [] });
            expect(content).to.contain('# STANDALONE_PORT=8082');
            expect(content).to.contain('# THEIA_PORT=3000');
            expect(content).not.to.contain('# GLSP_SERVER_PORT');
        });

        it('should set server type to node and start cmd when server-node is present', () => {
            const repos: GLSPRepo[] = ['glsp-server-node'];
            const content = generatePlaywrightEnvContent({ dir: tempDir, discoveredRepos: repos });
            expect(content).to.contain('GLSP_SERVER_TYPE=node');
            expect(content).to.contain('GLSP_SERVER_START_CMD=npx glsp repo server-node start');
            expect(content).not.to.match(/^# GLSP_SERVER_START_CMD/m);
        });

        it('should set server type to java and start cmd when only glsp-server is present', () => {
            const repos: GLSPRepo[] = ['glsp-server'];
            const content = generatePlaywrightEnvContent({ dir: tempDir, discoveredRepos: repos });
            expect(content).to.contain('GLSP_SERVER_TYPE=java');
            expect(content).to.contain('GLSP_SERVER_START_CMD=npx glsp repo server-java start');
            expect(content).not.to.match(/^# GLSP_SERVER_START_CMD/m);
        });

        it('should prefer server-node over glsp-server when both are present', () => {
            const repos: GLSPRepo[] = ['glsp-server-node', 'glsp-server'];
            const content = generatePlaywrightEnvContent({ dir: tempDir, discoveredRepos: repos });
            expect(content).to.contain('GLSP_SERVER_TYPE=node');
            expect(content).to.contain('GLSP_SERVER_START_CMD=npx glsp repo server-node start');
        });

        it('should set server type to unknown and comment out start cmd when no server repo is present', () => {
            const content = generatePlaywrightEnvContent({ dir: tempDir, discoveredRepos: [] });
            expect(content).to.contain('GLSP_SERVER_TYPE=unknown');
            expect(content).to.match(/^# GLSP_SERVER_START_CMD/m);
        });

        it('should enable standalone start cmd when client and server-node are present', () => {
            const repos: GLSPRepo[] = ['glsp-client', 'glsp-server-node'];
            const content = generatePlaywrightEnvContent({ dir: tempDir, discoveredRepos: repos });
            expect(content).to.contain('STANDALONE_START_CMD=npx glsp repo client start');
            expect(content).not.to.match(/^# STANDALONE_START_CMD/m);
        });

        it('should comment out standalone start cmd when repos are missing', () => {
            const content = generatePlaywrightEnvContent({ dir: tempDir, discoveredRepos: ['glsp-client'] });
            expect(content).to.match(/^# STANDALONE_START_CMD/m);
        });

        it('should comment out browser command when bundle does not exist', () => {
            createRepoDirs('glsp-client', 'glsp-server-node');
            const repos: GLSPRepo[] = ['glsp-client', 'glsp-server-node'];
            const content = generatePlaywrightEnvContent({ dir: tempDir, discoveredRepos: repos });
            expect(content).to.match(/^# STANDALONE_BROWSER_START_CMD/m);
        });

        it('should enable browser command when bundle exists', () => {
            createRepoDirs('glsp-client', 'glsp-server-node');
            const bundlePath = path.join(tempDir, 'glsp-server-node', BROWSER_BUNDLE_PATH);
            fs.mkdirSync(path.dirname(bundlePath), { recursive: true });
            fs.writeFileSync(bundlePath, 'fake-bundle');

            const repos: GLSPRepo[] = ['glsp-client', 'glsp-server-node'];
            const content = generatePlaywrightEnvContent({ dir: tempDir, discoveredRepos: repos });
            expect(content).to.match(/^STANDALONE_BROWSER_START_CMD=/m);
            expect(content).to.contain(bundlePath);
        });

        it('should enable theia command when theia repo is present', () => {
            const content = generatePlaywrightEnvContent({ dir: tempDir, discoveredRepos: ['glsp-theia-integration'] });
            expect(content).to.contain('THEIA_START_CMD=npx glsp repo theia start');
            expect(content).not.to.match(/^# THEIA_START_CMD/m);
        });

        it('should comment out theia command when repo is missing', () => {
            const content = generatePlaywrightEnvContent({ dir: tempDir, discoveredRepos: [] });
            expect(content).to.match(/^# THEIA_START_CMD/m);
        });

        it('should enable vscode section when vscode repo is present', () => {
            createRepoDirs('glsp-vscode-integration');
            const content = generatePlaywrightEnvContent({ dir: tempDir, discoveredRepos: ['glsp-vscode-integration'] });
            expect(content).to.contain('VSCODE_VSIX_ID=eclipse-glsp.workflow-vscode-example');
            expect(content).not.to.match(/^# VSCODE_VSIX_ID/m);
        });

        it('should comment out vscode section when repo is missing', () => {
            const content = generatePlaywrightEnvContent({ dir: tempDir, discoveredRepos: [] });
            expect(content).to.match(/^# VSCODE_VSIX_ID/m);
        });

        it('should use npx prefix in all commands', () => {
            createRepoDirs('glsp-client', 'glsp-server-node', 'glsp-theia-integration');
            const repos: GLSPRepo[] = ['glsp-client', 'glsp-server-node', 'glsp-theia-integration'];
            const content = generatePlaywrightEnvContent({ dir: tempDir, discoveredRepos: repos });
            const cmdLines = content.split('\n').filter(l => l.match(/^[^#].*_(?:START_CMD|START_CMD)=/));
            for (const line of cmdLines) {
                expect(line).to.match(/=npx glsp /);
            }
        });

        it('should produce complete env content for a full workspace', () => {
            createRepoDirs('glsp-client', 'glsp-server-node', 'glsp-theia-integration', 'glsp-vscode-integration');
            const repos: GLSPRepo[] = ['glsp-client', 'glsp-server-node', 'glsp-theia-integration', 'glsp-vscode-integration'];
            const content = generatePlaywrightEnvContent({ dir: tempDir, discoveredRepos: repos });
            expect(content).to.contain('GLSP_SERVER_START_CMD=');
            expect(content).to.contain('STANDALONE_START_CMD=');
            expect(content).to.contain('THEIA_START_CMD=');
            expect(content).to.contain('VSCODE_VSIX_ID=');
        });
    });
});
