/********************************************************************************
 * Copyright (c) 2026 EclipseSource and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License v. 2.0 are satisfied: GNU General Public License, version 2
 * with the GNU Classpath Exception which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 ********************************************************************************/

import { expect } from 'chai';
import * as fs from 'fs';
import * as path from 'path';
import { cliDiag, runCli } from '../../helpers/cli-helper';
import { cleanupTempDir, createTempDir } from '../../helpers/test-helper';

describe('repo commands — playwright', function () {
    let workDir: string;

    before(function () {
        workDir = createTempDir();

        const cloneResult = runCli(['repo', 'clone', '--preset', 'playwright', '-d', workDir]);
        expect(cloneResult.exitCode, `clone failed:\n${cliDiag(cloneResult)}`).to.equal(0);
    });

    after(function () {
        cleanupTempDir(workDir);
    });

    describe('env', function () {
        it('should generate a .env file in the default target directory', function () {
            const result = runCli(['repo', 'glsp-playwright', 'env', '-d', workDir]);
            expect(result.exitCode, cliDiag(result)).to.equal(0);

            const envFile = path.join(workDir, 'glsp-playwright', 'examples', 'workflow-test', '.env');
            expect(fs.existsSync(envFile), '.env file should exist').to.be.true;

            const content = fs.readFileSync(envFile, 'utf-8');
            expect(content).to.contain('# Generated by: glsp repo playwright env');
            expect(content).to.contain('GLSP_SERVER_START_CMD=');
            expect(content).to.contain('STANDALONE_START_CMD=');
        });

        it('should generate a .env file in a custom target directory', function () {
            const customTarget = path.join(workDir, 'custom-env-output');
            const result = runCli(['repo', 'glsp-playwright', 'env', '-d', workDir, '-t', customTarget]);
            expect(result.exitCode, cliDiag(result)).to.equal(0);

            const envFile = path.join(customTarget, '.env');
            expect(fs.existsSync(envFile), '.env file should exist at custom path').to.be.true;

            const content = fs.readFileSync(envFile, 'utf-8');
            expect(content).to.contain('# Generated by: glsp repo playwright env');
        });

        it('should include theia commands since theia-integration is cloned', function () {
            const result = runCli(['repo', 'glsp-playwright', 'env', '-d', workDir]);
            expect(result.exitCode, cliDiag(result)).to.equal(0);

            const envFile = path.join(workDir, 'glsp-playwright', 'examples', 'workflow-test', '.env');
            const content = fs.readFileSync(envFile, 'utf-8');
            expect(content).to.match(/^THEIA_START_CMD=/m);
        });

        it('should include vscode section since vscode-integration is cloned', function () {
            const envFile = path.join(workDir, 'glsp-playwright', 'examples', 'workflow-test', '.env');
            const content = fs.readFileSync(envFile, 'utf-8');
            expect(content).to.match(/^VSCODE_VSIX_ID=/m);
        });

        it('should fail when glsp-playwright is not cloned and no --target-dir given', function () {
            const emptyDir = createTempDir();
            try {
                fs.mkdirSync(path.join(emptyDir, 'glsp-client'));
                const result = runCli(['repo', 'glsp-playwright', 'env', '-d', emptyDir]);
                expect(result.exitCode).to.not.equal(0);
                const output = result.stdout + result.stderr;
                expect(output).to.contain('--target-dir');
            } finally {
                cleanupTempDir(emptyDir);
            }
        });
    });
});
