name: CI

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22.x
      - name: Build
        run: yarn install
      - name: Check for uncommitted changes in yarn.lock
        run: |
          if git diff --name-only | grep -q "^yarn.lock"; then
            echo "::error::The yarn.lock file has uncommitted changes!"
            exit 1
          fi
  lint:
    name: Lint
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22.x
      - name: Install
        run: |
          yarn install
      - name: Create eslint json report
        run: |
          yarn lint:ci
      - name: Create summary
        if: always()
        run: |
          npm_config_yes=true npx github:10up/eslint-json-to-md#82ff16b --path ./eslint_report.json --output ./eslint_report.md
          cat eslint_report.md >> $GITHUB_STEP_SUMMARY
